export const TF_OPTIONS = ['1m', '5m', '15m', '30m', '1h', '4h'];
export const BOARD_TABS = ['crypto', 'macro', 'stocks', 'politics', 'war', 'ai'];
const savedWorkspace = JSON.parse(localStorage.getItem('zai_workspace') || '{}');

export const state = {
  mode: 'ai',
  board: 'crypto',
  symbol: (localStorage.getItem('zai_symbol') || 'BTC').toUpperCase(),
  timeframe: localStorage.getItem('zai_timeframe') || '15m',
  apiKey: localStorage.getItem('zai_openrouter_key') || '',
  workspace: {
    equity: Number(savedWorkspace.equity ?? 1000),
    riskPct: Number(savedWorkspace.riskPct ?? 1),
    stopPct: Number(savedWorkspace.stopPct ?? 0.6),
    leverage: Number(savedWorkspace.leverage ?? 20),
  },
  liveStatus: {
    market: 'Connecting',
    news: 'Connecting',
    events: 'Connecting',
    liq: 'Connecting',
    scan: 'Connecting',
  },
  streams: { mark: null, liq: null, symbol: null },
  market: {
    lastPrice: 0,
    markPrice: 0,
    indexPrice: 0,
    dayChangePct: 0,
    quoteVolume: 0,
    baseVolume: 0,
    funding: 0,
    nextFundingTime: 0,
    openInterestUsd: 0,
    oiDeltaPct: 0,
    sentiment: 50,
    sentimentLabel: 'Neutral',
    spreadPct: 0,
    depthM: 0,
    bookBidNotional: 0,
    bookAskNotional: 0,
    topBid: 0,
    topAsk: 0,
    snapshots: [],
    stableHistory: [],
    flips: 0,
    drift: 0,
    persist: 0,
    mad: 0,
    series: [],
    phase: 'Booting live futures monitor…',
    liqLong: 0,
    liqShort: 0,
    liqWindowStart: Date.now(),
    longBreak: 0,
    shortBreak: 0,
  },
  scan: [],
  alerts: [],
  news: [],
  events: [],
  intelFeed: [],
  aiAnalysis: '',
  aiStatus: 'Idle',
  chat: [{ role: 'zai', text: 'Terminal online. Ask for bias, tradeability, liquidation pressure, or whether the setup is worth attention.' }],
  lastRender: {
    boardKey: '', newsKey: '', eventsKey: '', reportKey: '', liqKey: '', chartKey: '', intelKey: '',
    chatKey: '', alertsKey: '', scanKey: '', clockKey: '',
  },
};
